# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  config.vm.box = "bento/ubuntu-21.04"

  config.vm.hostname = "gojournal-vm"

  # support ssh -p 10322 vagrant@localhost to tunnel into guest
  config.vm.network "forwarded_port", guest: 22, host: 10322, host_ip: "127.0.0.1"

  # configure the VirtualBox VM
  config.vm.provider "virtualbox" do |vb|
    vb.name = "gojournal-vm"

    vb.memory = 8192
    vb.cpus = 4

    # Use Host I/O cache (speeds up disk performance)
    vb.customize ["storagectl", :id, "--name", "SATA Controller",
                  "--hostiocache", "on"]
    # Mark disk as an SSD (enables TRIM support)
    vb.customize ["storageattach", :id, "--storagectl", "SATA Controller",
                  "--port", "0",
                  "--discard", "on",
                  "--nonrotational", "on"]
  end

  # provision the machine
  #
  # NOTE: these scripts take 10-15 minutes to run
  config.vm.provision "shell", path: "vm-init.sh", privileged: false
  config.vm.provision "shell" do |s|
    s.path = "vm-setup.sh"
    s.privileged = false
    # you can also use -no-ocaml or -no-coq to skip those steps
    # (those are the slowest; FSCQ's dependencies take a lot of space)
    s.args = ["-no-fscq"]
  end
end
