# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  config.vm.box = "bento/ubuntu-21.04"

  config.vm.hostname = "gojournal-vm"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # support ssh -p 10322 vagrant@localhost to tunnel into guest
  config.vm.network "forwarded_port", guest: 22, host: 10322, host_ip: "127.0.0.1"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
    vb.name = "gojournal-vm"

    vb.memory = 8192
    vb.cpus = 4

    # Use Host I/O cache (speeds up disk performance)
    vb.customize ["storagectl", :id, "--name", "SATA Controller",
                  "--hostiocache", "on"]
    # Mark disk as an SSD (enables TRIM support)
    vb.customize ["storageattach", :id, "--storagectl", "SATA Controller",
                  "--port", "0",
                  "--discard", "on",
                  "--nonrotational", "on"]
  end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # provision the machine (note these scripts take 10-15 minutes to run)
  config.vm.provision "shell", path: "vm-init.sh", privileged: false
  config.vm.provision "shell" do |s|
    s.path = "vm-setup.sh"
    s.privileged = false
    s.args = ["-ocaml", "-coq"]
  end
end
